export type TransactionClassification =
  | 'unknown'
  | 'unknownInternal'
  | 'internalTransfer'
  | 'send'
  | 'receive'
  | 'transfer'
  | 'consolidate'
  | 'split'
  | 'shieldedIcs20Withdrawal'
  | 'ibcRelayAction'
  | 'validatorDefinition'
  | 'validatorVote'
  | 'proposalSubmit'
  | 'complianceRegisterAsset'
  | 'complianceRegisterUser';
